[project]
name = "funlbm"
version = "1.1.50"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "funutil>=1.0.14", "funvtk>=1.0.9", "torch>=2.2.0", "transforms3d>=0.4.2",]
