[project]
name = "funlbm"
version = "1.1.18"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [ "funutil>=1.0.12", "funvtk>=1.0.9", "torch>=2.5.0", "transforms3d>=0.4.2",]
